/* Auto-generated by genmsg_cpp for file /home/correlllab/ros/dynamixel_motor/dynamixel_controllers/srv/SetCompliancePunch.srv */
#ifndef DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEPUNCH_H
#define DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEPUNCH_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace dynamixel_controllers
{
template <class ContainerAllocator>
struct SetCompliancePunchRequest_ : public ros::Message
{
  typedef SetCompliancePunchRequest_<ContainerAllocator> Type;

  SetCompliancePunchRequest_()
  : punch(0)
  {
  }

  SetCompliancePunchRequest_(const ContainerAllocator& _alloc)
  : punch(0)
  {
  }

  typedef uint8_t _punch_type;
  uint8_t punch;


private:
  static const char* __s_getDataType_() { return "dynamixel_controllers/SetCompliancePunchRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "6f1db06d3f143058321215213d1c3bef"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "6f1db06d3f143058321215213d1c3bef"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
uint8 punch\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, punch);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, punch);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(punch);
    return size;
  }

  typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetCompliancePunchRequest
typedef  ::dynamixel_controllers::SetCompliancePunchRequest_<std::allocator<void> > SetCompliancePunchRequest;

typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchRequest> SetCompliancePunchRequestPtr;
typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchRequest const> SetCompliancePunchRequestConstPtr;


template <class ContainerAllocator>
struct SetCompliancePunchResponse_ : public ros::Message
{
  typedef SetCompliancePunchResponse_<ContainerAllocator> Type;

  SetCompliancePunchResponse_()
  {
  }

  SetCompliancePunchResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "dynamixel_controllers/SetCompliancePunchResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "6f1db06d3f143058321215213d1c3bef"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetCompliancePunchResponse
typedef  ::dynamixel_controllers::SetCompliancePunchResponse_<std::allocator<void> > SetCompliancePunchResponse;

typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchResponse> SetCompliancePunchResponsePtr;
typedef boost::shared_ptr< ::dynamixel_controllers::SetCompliancePunchResponse const> SetCompliancePunchResponseConstPtr;

struct SetCompliancePunch
{

typedef SetCompliancePunchRequest Request;
typedef SetCompliancePunchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetCompliancePunch
} // namespace dynamixel_controllers

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f1db06d3f143058321215213d1c3bef";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f1db06d3f143058ULL;
  static const uint64_t static_value2 = 0x321215213d1c3befULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetCompliancePunchRequest";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
uint8 punch\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetCompliancePunchResponse";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.punch);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetCompliancePunchRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetCompliancePunchResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<dynamixel_controllers::SetCompliancePunch> {
  static const char* value() 
  {
    return "6f1db06d3f143058321215213d1c3bef";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunch&) { return value(); } 
};

template<>
struct DataType<dynamixel_controllers::SetCompliancePunch> {
  static const char* value() 
  {
    return "dynamixel_controllers/SetCompliancePunch";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunch&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f1db06d3f143058321215213d1c3bef";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetCompliancePunch";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunchRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f1db06d3f143058321215213d1c3bef";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetCompliancePunch";
  }

  static const char* value(const dynamixel_controllers::SetCompliancePunchResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEPUNCH_H

