; Auto-generated. Do not edit!


(cl:in-package control_msgs-msg)


;//! \htmlinclude PointHeadActionFeedback.msg.html

(cl:defclass <PointHeadActionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PointHeadActionFeedback (<PointHeadActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointHeadActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointHeadActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_msgs-msg:<PointHeadActionFeedback> is deprecated: use control_msgs-msg:PointHeadActionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointHeadActionFeedback>) ostream)
  "Serializes a message object of type '<PointHeadActionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointHeadActionFeedback>) istream)
  "Deserializes a message object of type '<PointHeadActionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointHeadActionFeedback>)))
  "Returns string type for a message object of type '<PointHeadActionFeedback>"
  "control_msgs/PointHeadActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointHeadActionFeedback)))
  "Returns string type for a message object of type 'PointHeadActionFeedback"
  "control_msgs/PointHeadActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointHeadActionFeedback>)))
  "Returns md5sum for a message object of type '<PointHeadActionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointHeadActionFeedback)))
  "Returns md5sum for a message object of type 'PointHeadActionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointHeadActionFeedback>)))
  "Returns full string definition for message of type '<PointHeadActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointHeadActionFeedback)))
  "Returns full string definition for message of type 'PointHeadActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointHeadActionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointHeadActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PointHeadActionFeedback
))
