; Auto-generated. Do not edit!


(cl:in-package control_msgs-msg)


;//! \htmlinclude PointHeadActionResult.msg.html

(cl:defclass <PointHeadActionResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PointHeadActionResult (<PointHeadActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointHeadActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointHeadActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name control_msgs-msg:<PointHeadActionResult> is deprecated: use control_msgs-msg:PointHeadActionResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointHeadActionResult>) ostream)
  "Serializes a message object of type '<PointHeadActionResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointHeadActionResult>) istream)
  "Deserializes a message object of type '<PointHeadActionResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointHeadActionResult>)))
  "Returns string type for a message object of type '<PointHeadActionResult>"
  "control_msgs/PointHeadActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointHeadActionResult)))
  "Returns string type for a message object of type 'PointHeadActionResult"
  "control_msgs/PointHeadActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointHeadActionResult>)))
  "Returns md5sum for a message object of type '<PointHeadActionResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointHeadActionResult)))
  "Returns md5sum for a message object of type 'PointHeadActionResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointHeadActionResult>)))
  "Returns full string definition for message of type '<PointHeadActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointHeadActionResult)))
  "Returns full string definition for message of type 'PointHeadActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointHeadActionResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointHeadActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PointHeadActionResult
))
