/* Auto-generated by genmsg_cpp for file /home/correlllab/ros/control_msgs/control_msgs/msg/FollowJointTrajectoryResult.msg */
#ifndef CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYRESULT_H
#define CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYRESULT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace control_msgs
{
template <class ContainerAllocator>
struct FollowJointTrajectoryResult_ : public ros::Message
{
  typedef FollowJointTrajectoryResult_<ContainerAllocator> Type;

  FollowJointTrajectoryResult_()
  : error_code(0)
  {
  }

  FollowJointTrajectoryResult_(const ContainerAllocator& _alloc)
  : error_code(0)
  {
  }

  typedef int32_t _error_code_type;
  int32_t error_code;

  enum { SUCCESSFUL = 0 };
  enum { INVALID_GOAL = -1 };
  enum { INVALID_JOINTS = -2 };
  enum { OLD_HEADER_TIMESTAMP = -3 };
  enum { PATH_TOLERANCE_VIOLATED = -4 };
  enum { GOAL_TOLERANCE_VIOLATED = -5 };

private:
  static const char* __s_getDataType_() { return "control_msgs/FollowJointTrajectoryResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "6243274b5d629dc838814109754410d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 error_code\n\
int32 SUCCESSFUL = 0\n\
int32 INVALID_GOAL = -1\n\
int32 INVALID_JOINTS = -2\n\
int32 OLD_HEADER_TIMESTAMP = -3\n\
int32 PATH_TOLERANCE_VIOLATED = -4\n\
int32 GOAL_TOLERANCE_VIOLATED = -5\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, error_code);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, error_code);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(error_code);
    return size;
  }

  typedef boost::shared_ptr< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator>  const> ConstPtr;
}; // struct FollowJointTrajectoryResult
typedef  ::control_msgs::FollowJointTrajectoryResult_<std::allocator<void> > FollowJointTrajectoryResult;

typedef boost::shared_ptr< ::control_msgs::FollowJointTrajectoryResult> FollowJointTrajectoryResultPtr;
typedef boost::shared_ptr< ::control_msgs::FollowJointTrajectoryResult const> FollowJointTrajectoryResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6243274b5d629dc838814109754410d5";
  }

  static const char* value(const  ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6243274b5d629dc8ULL;
  static const uint64_t static_value2 = 0x38814109754410d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "control_msgs/FollowJointTrajectoryResult";
  }

  static const char* value(const  ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 error_code\n\
int32 SUCCESSFUL = 0\n\
int32 INVALID_GOAL = -1\n\
int32 INVALID_JOINTS = -2\n\
int32 OLD_HEADER_TIMESTAMP = -3\n\
int32 PATH_TOLERANCE_VIOLATED = -4\n\
int32 GOAL_TOLERANCE_VIOLATED = -5\n\
\n\
\n\
";
  }

  static const char* value(const  ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.error_code);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FollowJointTrajectoryResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::control_msgs::FollowJointTrajectoryResult_<ContainerAllocator> & v) 
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYRESULT_H

