/* Auto-generated by genmsg_cpp for file /home/correlllab/ros/control_msgs/control_msgs/msg/PointHeadActionFeedback.msg */
#ifndef CONTROL_MSGS_MESSAGE_POINTHEADACTIONFEEDBACK_H
#define CONTROL_MSGS_MESSAGE_POINTHEADACTIONFEEDBACK_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace control_msgs
{
template <class ContainerAllocator>
struct PointHeadActionFeedback_ : public ros::Message
{
  typedef PointHeadActionFeedback_<ContainerAllocator> Type;

  PointHeadActionFeedback_()
  {
  }

  PointHeadActionFeedback_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "control_msgs/PointHeadActionFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct PointHeadActionFeedback
typedef  ::control_msgs::PointHeadActionFeedback_<std::allocator<void> > PointHeadActionFeedback;

typedef boost::shared_ptr< ::control_msgs::PointHeadActionFeedback> PointHeadActionFeedbackPtr;
typedef boost::shared_ptr< ::control_msgs::PointHeadActionFeedback const> PointHeadActionFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "control_msgs/PointHeadActionFeedback";
  }

  static const char* value(const  ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
";
  }

  static const char* value(const  ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PointHeadActionFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::control_msgs::PointHeadActionFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_POINTHEADACTIONFEEDBACK_H

